---
abstract: 'Speed up File::KDBX'
author:
  - 'Charles McGarvey <ccm@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-KDBX-XS
no_index:
  directory:
    - eg
    - libtomcrypt
    - t
    - xt
provides:
  File::KDBX::XS:
    file: lib/File/KDBX/XS.pm
    version: '0.900'
requires:
  XSLoader: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/chazmcgarvey/File-KDBX-XS/issues
  homepage: https://github.com/chazmcgarvey/File-KDBX-XS
  repository: https://github.com/chazmcgarvey/File-KDBX-XS.git
version: '0.900'
x_authority: cpan:CCM
x_contributors:
  - 'Karel Miko <mic@cpan.org>'
x_generated_by_perl: v5.34.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
