name: linux

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  unit-tests:
    name: "Test perl v${{ matrix.perl }} on Linux"

    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:${{ matrix.perl }}

    strategy:
      fail-fast: false
      matrix:
        perl:
          - "5.34"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install author dependencies
        run: dzil authordeps --missing |cpanm -n
      - name: Install module dependencies
        run: dzil listdeps --develop --missing |cpanm -n
      - name: Run tests
        run: dzil smoke --author --release
